@startuml

title UC10 - Seriar (não automaticamente) Candidaturas de Anúncio

actor "Colaborador da Organização"
activate "Colaborador da Organização"

"Colaborador da Organização" -> ":Sistema" : 1 inicia o processo não automático de seriação dos candidatos à realização de um anúncio
activate ":Sistema"

":Sistema" --> "Colaborador da Organização": 2 mostra os anúncios publicados pelo colaborador em fase de seriação não automática, e que ainda não foram seriados, e pede-lhe para escolher um
deactivate ":Sistema"

"Colaborador da Organização" -> ":Sistema": 3 seleciona um anúncio
activate ":Sistema"

":Sistema" --> "Colaborador da Organização": 4 mostra as candidaturas existentes e solicita a sua classificação
deactivate ":Sistema"

loop 

"Colaborador da Organização" -> ":Sistema": 5 classifica a candidatura
activate ":Sistema"

end

":Sistema" --> "Colaborador da Organização": 6 mostra os colaboradores da organização e pede para selecionar outros participantes
deactivate ":Sistema"

loop

"Colaborador da Organização" -> ":Sistema": 7 seleciona outros colaboradores participantes
activate ":Sistema"

end

":Sistema" --> "Colaborador da Organização": 8 apresenta os dados e solicita confirmação
deactivate ":Sistema"

"Colaborador da Organização" -> ":Sistema": 9 confirma
activate ":Sistema"

":Sistema" --> "Colaborador da Organização": 10 informa o sucesso da operação
deactivate ":Sistema"

deactivate "Colaborador da Organização"

@enduml