@startuml

title UC01 - Registar Organização

actor "Utilizador não registado"
activate "Utilizador não registado"

skinparam sequenceMessageAlign left
"Utilizador não registado" -> Sistema: 1. Registar Organização
Sistema --> "Utilizador não registado": 2. Solicita dados da organização (nome, NIF, endereço, telefone, website, email) e sobre o gestor (nome, funçao, telefone, email)

"Utilizador não registado" -> Sistema: 3. Introduz os dados solicitados
"Utilizador não registado" <-- Sistema: 4. Apresenta os dados inseridos e solicita confirmação

"Utilizador não registado" -> Sistema: 5. Confirma os dados inseridos
"Utilizador não registado" <-- Sistema: 6. Operação bem sucedida

@enduml