@startuml

title UC07a - Adicionar Habilitações Académicas

actor Administrativo
participant ":Sistema" as Sistema

activate Administrativo

Administrativo -> Sistema : 1 O administrativo inicia o processo de adicionar habilitações académicas do freelancer
activate Sistema

loop
Sistema --> Administrativo: 2 solicita o email do Freelancer (email)
Administrativo -> Sistema: 3 O administrativo selecciona o email do Freelancer a partir da lista fornecida
Administrativo -> Sistema: 4 introduz as habilitaçoes académicas (grau, nomeCurso, instituicao, mediaCurso)
Sistema --> Administrativo: 5 Operação bem sucedida
end

deactivate Administrativo
deactivate Sistema

@enduml