@startuml

title UC06 - Especificar Tarefa

actor Colaborador 
participant ":EspecificarTarefaUI" as EspecificarTarefaUI
participant ":EspecificarTarefaCTRL" as EspecificarTarefaCTRL
participant ":raa: RepositorioAreaActividade" as RepositorioAreaActividade
participant "rc:RepositorioCategoria" as RepositorioCategoria
participant "rcct:RepositorioCaracterizacaoCT" as RepositorioCCT
participant "gu: GestaoUtilizadores" as GestaoUtilizadoresCTRL
participant "ro:RepositorioOrganizacao" as RepositorioOrganizacao
participant "rt:RepositorioTarefa" as RepositorioTarefa

activate Colaborador
Colaborador -> EspecificarTarefaUI: Inicia a especificação de uma tarefa
activate EspecificarTarefaUI
EspecificarTarefaUI -> GestaoUtilizadoresCTRL: getEmail()
activate GestaoUtilizadoresCTRL
GestaoUtilizadoresCTRL --> EspecificarTarefaUI: emailColaborador
deactivate GestaoUtilizadoresCTRL

EspecificarTarefaUI -> EspecificarTarefaCTRL: findNifByEmail(emailColaborador)
activate EspecificarTarefaCTRL
EspecificarTarefaCTRL -> RepositorioOrganizacao: findNifByEmail(emailColaborador)
activate RepositorioOrganizacao
RepositorioOrganizacao --> EspecificarTarefaCTRL: nifOrganizacao
deactivate RepositorioOrganizacao
EspecificarTarefaCTRL --> EspecificarTarefaUI: nifOrganizacao
deactivate EspecificarTarefaCTRL

EspecificarTarefaUI -> EspecificarTarefaCTRL: getAllAreasActividade()
activate EspecificarTarefaCTRL
EspecificarTarefaCTRL -> RepositorioAreaActividade: getAllAreasActividade()
activate RepositorioAreaActividade
RepositorioAreaActividade --> EspecificarTarefaCTRL: areasActividade
deactivate RepositorioAreaActividade
EspecificarTarefaCTRL --> EspecificarTarefaUI: areasActividade
deactivate EspecificarTarefaCTRL
EspecificarTarefaUI --> Colaborador: mostra as áreas de actividade
deactivate EspecificarTarefaUI

Colaborador -> EspecificarTarefaUI: selecciona área de actividade
activate EspecificarTarefaUI
EspecificarTarefaUI -> EspecificarTarefaCTRL: getAllCategoriasTarefa(codigoAreaActividade)
activate EspecificarTarefaCTRL
EspecificarTarefaCTRL -> RepositorioCategoria: getAllCategoriasTarefa(codigoAreaActividade)
activate RepositorioCategoria
RepositorioCategoria --> EspecificarTarefaCTRL: categorias
deactivate RepositorioCategoria
EspecificarTarefaCTRL --> EspecificarTarefaUI: categorias
deactivate EspecificarTarefaCTRL
EspecificarTarefaUI --> Colaborador: mostra as categorias de tarefa
deactivate EspecificarTarefaUI

Colaborador -> EspecificarTarefaUI: selecciona a categoria de tarefa
activate EspecificarTarefaUI
EspecificarTarefaUI -> EspecificarTarefaCTRL: getAllCaracterizacaoCompetenciaTecnica(codigoCategoria)
activate EspecificarTarefaCTRL
EspecificarTarefaCTRL -> RepositorioCCT: getAllCaracterizacaoCompetenciaTecnica(codigoCategoria)
activate RepositorioCCT
RepositorioCCT --> EspecificarTarefaCTRL: caracterizacoesCT
deactivate RepositorioCCT
EspecificarTarefaCTRL --> EspecificarTarefaUI: caracterizacoesCT
deactivate EspecificarTarefaCTRL
EspecificarTarefaUI --> Colaborador: mostra as caracterizações \nde competências técnicas correspondentes à categoria

Colaborador -> EspecificarTarefaUI: introduz os restantes dados
activate EspecificarTarefaUI
EspecificarTarefaUI -> EspecificarTarefaCTRL: registarTarefa(codigoCategoria, \nreferencia, nifOrganizacao, designacao, descInforma, \ndescTenica, custoEstimado, duracaoEstimada, emailColaborador)
activate EspecificarTarefaCTRL
create Tarefa
EspecificarTarefaCTRL -> Tarefa: new Tarefa(codigoCategoria, \nreferencia, nifOrganizacao, designacao, descInforma, \ndescTenica, custoEstimado, duracaoEstimada, emailColaborador)
EspecificarTarefaCTRL -> RepositorioTarefa: save(tarefa)
activate RepositorioTarefa
RepositorioTarefa -> RepositorioTarefa: save(tarefa)
RepositorioTarefa --> EspecificarTarefaCTRL: tarefa
deactivate RepositorioTarefa
EspecificarTarefaCTRL --> EspecificarTarefaUI: tarefa
deactivate EspecificarTarefaCTRL
EspecificarTarefaUI --> Colaborador: mostra mensagem de sucesso 







@enduml