@startuml

title UC04 - Especificar Competência Técnica

actor Administrador
participant ":Sistema" as Sistema

activate Administrador

Administrador -> Sistema : 1 inicia a especificação de uma competência técnica
activate Sistema

Sistema --> Administrador: 2 solicita os dados (código, área de atividade, descrição breve e detalhada)
deactivate Sistema

Administrador -> Sistema: 3 introduz os dados solicitados
activate Sistema

loop

Sistema --> Administrador: 4 solicita os vários graus de proficiência aplicáveis
deactivate Sistema

Administrador -> Sistema: 5 introduz os dados de cada grau
activate Sistema

end


Sistema --> Administrador: 6 informa operação bem sucedida
deactivate Sistema
@enduml