@startuml

left to right direction
title Modelo Relacional

hide circle
'skinparam linetype ortho

entity "Organizacao" {
    nif: text {PK}     
    --
    nome: text {NN}
    website: text
    telefone: text {NN}
    email: text {NN, UK}
    emailGestor: text {FK, NN}
    idEnderecoPostal: number {FK}
}

entity "Colaborador" {
    email: text {PK, FK}
    --
    funcao: text
    telefone: text
    nifOrganizacao: text {FK}

}

entity "ColaboradorClassificacao" {
    emailColaborador: text {PK, FK}
    idClassificacao: int {PK, FK}
}

entity "Utilizador" {
    email: text {PK}
    --
    nome: text {NN}
    password: text {NN}
}

entity "Administrativo" {
    email: text {PK, FK}
    --
}

entity "Categoria" {
    codigoCategoria: text {PK}
    --
    descBreve: text {NN, UK}
    descDetalhada: text
    codigoAreaActividade: text {FK}
}

entity "CompetenciaTecnica" {
    codigoCompTecnica: text {PK}
    --
    descBreve: text {NN, UK}
    descDetalhada: text
    idCaracterCT: text {FK}
    codigoAreaActividade: text {FK}
}

entity "AreaActividade" {
    codigoAreaActividade: text {PK}
    --
    descBreve: text {NN, UK}
    descDetalhada: text
}

entity "GrauProficiencia" {
    idGrauProficiencia: number {PK}
    --
    valor: integer {NN, UK}
    designacao: text {NN}
    codigoCompTecnica: text {FK}
}

entity "Freelancer" {
    email: text {PK, FK}
    --
    telefone: text
    nif: text
    idEnderecoPostal: text {FK}
}

entity "EnderecoPostal" {
    idEnderecoPostal: text {PK}
    --
    arruamento: text 
    numeroPorta: text 
    localidade: text 
    codigoPostal: text 
}

entity "Tarefa" {
    nifOrganizacao: text {PK, FK}
    referencia: text {PK}
    --
    designacao: text {NN}
    descInformal: text
    descTecnica: text
    duracaoEstimada: integer {NN}
    custoEstimado: number {NN}
    idCategoria: texto {FK}
    emailColaborador: texto {FK}
}

entity "Anuncio" {
    idAnuncio {PK}
    --
    referenciaTarefa: text {FK}
    nifOrganizacao: text {FK}
    dataInicioPublicacao: date {NN}
    dataFimPublicacao: date {NN}
    dataInicioCandidatura: date {NN}
    dataFimCandidatura: date {NN}
    dataInicioSeriacao: date {NN} 
    dataFimSeriacao: date {NN}
    idProcessoSeriacao: number {FK}
    idTipoRegimento: number {FK}
}


entity "ProcessoSeriacao" {
    idProcessoSeriacao: number {PK}
    --
    dataRealizacao: date {NN}
    idAnuncio: int {FK}
}

entity "TipoRegimento" {
    idTipoRegimento: number {PK}
    --
    designacao: text {NN, UK}
    descricaoRegras: text {NN}
}

entity "Classificacao" {
    idClassificacao: number {PK}
    --
    lugar: integer {NN, UK}
    idProcessoSeriacao: text {FK}
    idCandidatura: int {FK}
}

entity "Candidatura" {
    idCandidatura: number {PK}
    --
    valorPretendido: number {NN}
    numeroDias: integer {NN}
    txtApresentacao: text
    txtMotivacao: text
    idAnuncio: number {FK}
    emailFreelancer: text {FK}
}

entity "HabilitacaoAcademica" {
    idHabilitacaoAcademica: number{PK}
    --
    grau: text {NN}
    designacaoCurso: text {NN}
    nomeInstituicao: text {NN}
    mediaCurso: number {NN}
}

entity "ReconhecimentoGP" {
    idGrauProficiencia: {PK, FK}
    emailFreelancer: text {PK, FK}
    --
    dataReconhecimento: date {NN}
}

entity "FreelancerHabAcademica" {
    emailFreelancer: text {PK, FK}
    idHabilitacaoAcademica: number {PK, FK}
}

entity "CaracterCT" {
    idCaracterCT: number {PK}
    --
    obrigatoria: boolean {NN}
    grauProfMinimo: text {FK, NN}
    codigoCategoria: text {FK}
}

AreaActividade ||--|{ Categoria
Freelancer |o--|| Utilizador
Administrativo |o--|| Utilizador
AreaActividade ||--|{ CompetenciaTecnica
CompetenciaTecnica ||--|{ GrauProficiencia
Colaborador ||--|{ Tarefa
Categoria ||--|{ Tarefa
Tarefa ||--o| Anuncio
Organizacao ||--|{ Colaborador
Colaborador |o--|| Utilizador
Anuncio ||--|{ Candidatura
Candidatura ||--|| Classificacao
Freelancer||--o{ Candidatura
Organizacao ||--|| EnderecoPostal
Freelancer ||--|| EnderecoPostal
Anuncio ||--|| ProcessoSeriacao
Anuncio }|--|| TipoRegimento
ProcessoSeriacao ||--|| Classificacao
Freelancer ||--|{ FreelancerHabAcademica
HabilitacaoAcademica ||--|{ FreelancerHabAcademica
Freelancer ||--|{ ReconhecimentoGP
ReconhecimentoGP }|--|| GrauProficiencia
CaracterCT }|--|| Categoria
CaracterCT }|--|| GrauProficiencia
Classificacao ||--|{ ColaboradorClassificacao
Colaborador ||--|{ ColaboradorClassificacao


@enduml