@startuml

title UC07 - Registar Freelancer

class RegistarFreelancerUI {
}

class RegistarFreelancerController {
}

class RegistoFreelancer {
}

class Plataforma {
}

class Freelancer {
}

class AutorizacaoFacade {
}

interface AlgoritmoGeradorPasswords {
}

RegistarFreelancerUI --o RegistarFreelancerController
Administrativo --> UC11_UI
UC11_UI --> UC11_Controller
UC11_Controller --> Freelancer

@enduml