@startuml

title UC07 - Registar Freelancer

actor Administrativo
participant ":Sistema" as Sistema

activate Administrativo

Administrativo -> Sistema : 1 registar freelancer
activate Sistema

Sistema --> Administrativo: 2 solicita os dados  do freelancer (nome, NIF, endereço postal, contacto telefónico, email)

Administrativo -> Sistema: 3 introduz os dados solicitados
Sistema --> Administrativo: 4 Operação bem sucedida

deactivate Administrativo
deactivate Sistema

@enduml