@startuml

title UC07 - Registar Freelancer

actor Administrativo
participant ":Sistema" as Sistema

activate Administrativo

Administrativo -> Sistema : 1 registar freelancer
activate Sistema

Sistema --> Administrativo: 2 solicita os dados  do freelancer (nome, NIF, endereço postal, contacto telefónico, email)

Administrativo -> Sistema: 3 introduz os dados solicitados
Sistema --> Administrativo: 4 Operação bem sucedida

loop
Administrativo -> Sistema : 5 Introduz os dados de habilitações académicas (grau, designação do curso, instituição que concedeu o grau e média do curso)
Sistema --> Administrativo : 6 Operação bem sucedida
end

loop
Administrativo -> Sistema: 7 introduz os reconhecimentos de competências técnicas (data, competência técnica e grau de proficiência)
Sistema --> Administrativo: 8 Operação bem sucedida
end


deactivate Administrativo
deactivate Sistema

@enduml