@startuml

title UC07 - Registar Freelancer

participant "Administrativo" as Administrativo
participant "RegistarFreelancerUI" as RegistarFreelancerUI
participant "RegistarFreelancerCTRL" as RegistarFreelancerCTRL
participant "rf: RepositorioFreelancer" as RepositorioFreelancer


activate Administrativo
Administrativo -> RegistarFreelancerUI : inicia o registo de um freelancer( nome, NIF, endPostal, telefone, email)
activate RegistarFreelancerUI
RegistarFreelancerUI -> RegistarFreelancerCTRL: findByNif(nif)
activate RegistarFreelancerCTRL
RegistarFreelancerCTRL -> RepositorioFreelancer: findByNif(nif)
activate RepositorioFreelancer
alt exist true
    RepositorioFreelancer --> RegistarFreelancerCTRL: nif já registado
    deactivate RepositorioFreelancer
    RegistarFreelancerCTRL --> RegistarFreelancerUI: nif já registado
    deactivate RegistarFreelancerCTRL
    RegistarFreelancerUI --> Administrativo: Freelancer com esse NIF já existe
    deactivate RegistarFreelancerUI

else exist false
    RepositorioFreelancer --> RegistarFreelancerCTRL: não existe
    activate RegistarFreelancerCTRL
    
end

RegistarFreelancerCTRL -> AlgoritmoGeradorPasswords: geraPassword
AlgoritmoGeradorPasswords --> RegistarFreelancerCTRL: password 

RegistarFreelancerCTRL -> GestaoUtilizadoresCTRL: registerUserWithRoles(email, nome, password, rolename)
activate GestaoUtilizadoresCTRL
GestaoUtilizadoresCTRL --> RegistarFreelancerCTRL: utilizadorFreelancer
deactivate GestaoUtilizadoresCTRL
create Freelancer
RegistarFreelancerCTRL -> Freelancer: new Freelancer(nome, password, NIF, endPostal, telefone, email)
RegistarFreelancerCTRL -> RepositorioFreelancer: save(freelancer)
activate RepositorioFreelancer
RepositorioFreelancer --> RegistarFreelancerCTRL: success
deactivate RepositorioFreelancer
RegistarFreelancerCTRL --> RegistarFreelancerUI: success
deactivate RegistarFreelancerCTRL
activate RegistarFreelancerUI
RegistarFreelancerUI --> Administrativo: operação bem sucedida
deactivate RegistarFreelancerUI
deactivate Administrativo




@enduml