@startuml

title UC07 - Registar Freelancer

left to right direction

class Plataforma <<Singleton>> {
    -String designacao
    --
    getRepositorioOrganizacao()
}

class RegistarFreelancerUI{
    --
    -novoFreelancer(nome, NIF, endereço postal, telefone, email)
    -registaFreelancer()

}

class RegistarFreelancerController{
    --
    novoFreelancer(NIF, telefone)
    validaFreelancer(c)
    registaFreelancer(c)
    registaUtilizadorComPapel(nome, email, password, "freelancer")
}

class Freelancer {
    -String nome
    -String NIF
    -String telefone
    -Email email
}

class EnderecoPostal {
    -String local
    -String codPostal
    -String localidade
}

class ReconhecimentoCT {
    -Date dataReconhecimento
}

class HabilitacaoAcademica {
    -String grau
    -String designacaoCurso
    -String nomeInstituicao
    -Double mediaCurso
}

class CompetenciaTecnica {
    -String codigo
    -String descBreve
    -String descDetalhada
}

class GrauProficiencia {
    -Integer valor
    -String designacao
}

class Utilizador {
    -String nome
    -Email email
    -Password password
}

class GestaoUtilizadoresFacade{
    --
    getGestaoUtilizadoresFacade()
}

class SessaoAtual{
    --
    getSessaoAtual()
}

class SessaoUtilizador{
    --
    getEmailUtilizador()
}

class RepositorioFreelancer{

}

interface AlgoritmoGeradorPasswords{
    --
    getAlgoritmoGeradorPasswords()
}

class Password{
    -String password
    --
    getPassword()
}

class UtilizadorComPapel{
}


class Email {
    -String email
    --
    getEmailUtilizador()
}

RegistarFreelancerUI ..> RegistarFreelancerController
RegistarFreelancerController ..> SessaoUtilizador
RegistarFreelancerController ..> Plataforma
RegistarFreelancerController ..> AlgoritmoGeradorPasswords
RegistarFreelancerController ..> GestaoUtilizadoresFacade
RegistarFreelancerController ..> UtilizadorComPapel
UtilizadorComPapel --> Utilizador
Utilizador -- Password
Utilizador -- Email
Email -- Organizacao: < possui
Freelancer --> ReconhecimentoCT: recebe(u) >
ReconhecimentoCT --> CompetenciaTecnica: relativa a >
CompetenciaTecnica --> GrauProficiencia: aplica >
Freelancer --> HabilitacaoAcademica: tem >


Freelancer --|> UtilizadorComPapel
UtilizadorComPapel --|> Utilizador
Email -- Utilizador: < possui
Password -- Utilizador: < possui


Freelancer -- SessaoAtual: tem >
RegistarFreelancerController ..> UtilizadorComPapel
Plataforma ..> RepositorioFreelancer


@enduml