@startuml
title UC02 - Definir Área de Actividade - Diagrama de Classes

class RegistarAreaActividadeUI {
}

class RegistarAreaActividadeController {
    --
    +registarAreaActividade(String cod, String dsBreve, String dsDet)
    +registaAreaActividade()
}

class RepositorioAreaActividade <<Singleton>>{
    --
    +AreaActividade registarAreaActividade(String cod, String dsBreve, String dsDet)
    -save(AreaActividade area)
    }


class AreaActividade {
    -String codigo
    -String descBreve
    -String descDetalhada
    --
    +AreaActividade(String cod, String descBreve, String descDet)
}

RegistarAreaActividadeUI ..> RegistarAreaActividadeController
RegistarAreaActividadeController ..> AreaActividade
RegistarAreaActividadeController ..> Plataforma
RegistarAreaActividadeController ..> RepositorioAreaActividade
Plataforma "1"-->"1" RepositorioAreaActividade 
RepositorioAreaActividade "1"-->"*" AreaActividade

@enduml