@startuml
title UC02 - Definir Área de Actividade - Diagrama de Sequência

actor Administrativo
participant Administrativo
participant RegistarAreaActividadeUI
participant RegistarAreaActividadeCTRL
participant "rat:RepositorioAreaAtividade" as RepositorioAreaAtividade
participant "area:AreaAtividade" as AreaAtividade

Administrativo -> RegistarAreaActividadeUI: 1. nova área de atividade
activate Administrativo
activate RegistarAreaActividadeUI
RegistarAreaActividadeUI --> Administrativo: 2. solicita dados(código, descrição breve e descrição detalhada)
deactivate RegistarAreaActividadeUI
Administrativo -> RegistarAreaActividadeUI: 3. introduz os dados solicitados
activate RegistarAreaActividadeUI
RegistarAreaActividadeUI -> RegistarAreaActividadeCTRL: 4. registarAreaActividade(cod, descBreve, descDet)
activate RegistarAreaActividadeCTRL
RegistarAreaActividadeCTRL -> RepositorioAreaAtividade: 4. area = save(cod, descBreve, descDet)
activate RepositorioAreaAtividade
RepositorioAreaAtividade --> AreaAtividade: 6. create(cod, descBreve, descDet)
RepositorioAreaAtividade --> RegistarAreaActividadeCTRL: 7. area
deactivate RepositorioAreaAtividade
RegistarAreaActividadeCTRL --> RegistarAreaActividadeUI: 8. area
deactivate RegistarAreaActividadeCTRL
RegistarAreaActividadeUI --> Administrativo: 9. operação bem sucedida
deactivate RegistarAreaActividadeUI

@enduml