@startuml

title UC10-A - Seriar Candidaturas de Anúncio (não automaticamente)

participant Colaborador
participant SeriarCandidaturasUI
participant SeriarCandidaturasCtrl
participant RepositorioAnuncio
participant RepositorioCandidatura
participant RepositorioClassificacao


activate Colaborador
Colaborador -> SeriarCandidaturasUI: Consulta anúncios com regime \nde seriação manual, em periodo \nde seriação, ainda não seriados
activate SeriarCandidaturasUI
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: getAllAnunciosASeriar\n(idRegimentoManual)
activate SeriarCandidaturasCtrl
SeriarCandidaturasCtrl -> RepositorioAnuncio: getAllAnunciosASeriar\n(idRegimentoManual)
activate RepositorioAnuncio
RepositorioAnuncio --> SeriarCandidaturasCtrl: listaAnunciosASeriar\n(idRegimentoManual)
deactivate RepositorioAnuncio
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: listaAnunciosASeriar\n(idRegimentoManual)
deactivate SeriarCandidaturasCtrl
alt (Não existem anúncios a seriar manualmente)
SeriarCandidaturasUI --> Colaborador: Não existem anúncios \ndisponiveis

else Existem anúncios a seriar manualmente 
SeriarCandidaturasUI --> Colaborador: Lista dos Anúncios a \nseriar manualmente
deactivate SeriarCandidaturasUI

Colaborador -> SeriarCandidaturasUI: Seleciona um anúncio a seriar
activate SeriarCandidaturasUI
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: getAllCandidaturas(idAnuncio)
activate SeriarCandidaturasCtrl
SeriarCandidaturasCtrl -> RepositorioCandidatura: getAllCandidaturas(idAnuncio)
activate RepositorioCandidatura
RepositorioCandidatura --> SeriarCandidaturasCtrl: listaCandidaturas(idAnuncio)
deactivate RepositorioCandidatura
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: listaCandidaturas(idAnuncio)
deactivate SeriarCandidaturasCtrl
SeriarCandidaturasUI --> Colaborador: Mostra a lista de candidaturas \nao anúncio e solicita a classificação \nde cada candidatura
deactivate SeriarCandidaturasUI



loop
Colaborador -> SeriarCandidaturasUI: Atribui uma classificação a uma \ndada candidatura
activate SeriarCandidaturasUI
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: setSeriacao\n(idCandidatura, posicao)
activate SeriarCandidaturasCtrl
SeriarCandidaturasCtrl -> RepositorioClassificacao: saveSeriacao(idAnuncio, idCandidatura, posicao)
activate RepositorioClassificacao
end loop
RepositorioClassificacao --> SeriarCandidaturasCtrl: listaCandidaturasSeriada(idAnuncio)
deactivate RepositorioClassificacao
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: listaCandidaturasSeriadas\n(idAnuncio)
deactivate SeriarCandidaturasCtrl
SeriarCandidaturasUI --> Colaborador: Mostra a lista seriada \nde candidaturas e solicita \nconfirmação

Colaborador -> SeriarCandidaturasUI: Confirma a seriação realizada

'\ninformar se houve mais colaboradores \npartipantes envolvidos na seriação

alt (Não existem colaboradores participantes adicionais)
Colaborador -> SeriarCandidaturasUI: Confirma a seriação e não indica 
end alt



end alt

@enduml