@startuml

participant Freelancer
participant "EditarCandidataturaUI" as EditarCandidataturaUI
participant "EditarCandidaturaCTRL" as EditarCandidaturaCTRL
participant RepositorioCandidatura


title UC11 - Editar Candidatura
activate Freelancer
Freelancer -> EditarCandidataturaUI : Consulta candidaturas editáveis
activate EditarCandidataturaUI
EditarCandidataturaUI -> EditarCandidaturaCTRL : getAllCandidaturasEditáveis \n(emailFreelancer)
activate EditarCandidaturaCTRL
EditarCandidaturaCTRL -> RepositorioCandidatura : getAllCandidaturasEditáveis()
activate RepositorioCandidatura
RepositorioCandidatura --> EditarCandidaturaCTRL : candidaturasEditáveis
deactivate RepositorioCandidatura
EditarCandidaturaCTRL --> EditarCandidataturaUI : candidaturasEditáveis
deactivate EditarCandidaturaCTRL
alt Não existem candidaturas editáveis
EditarCandidataturaUI --> Freelancer : Não existem candidaturas disponíveis
deactivate EditarCandidataturaUI
else existem candidaturas editáveis
Freelancer -> EditarCandidataturaUI : Seleciona candidatura
activate EditarCandidataturaUI
EditarCandidataturaUI -> EditarCandidaturaCTRL : getCandidatura(idCandidatura)
activate EditarCandidaturaCTRL
EditarCandidaturaCTRL -> RepositorioCandidatura : getCandidatura(idCandidatura)
activate RepositorioCandidatura
RepositorioCandidatura --> EditarCandidaturaCTRL : candidatura
deactivate RepositorioCandidatura
EditarCandidaturaCTRL --> EditarCandidataturaUI : candidatura
deactivate EditarCandidaturaCTRL
EditarCandidataturaUI --> Freelancer : Apresenta os dados registados \nSolicita confirmar/editar os dados
deactivate EditarCandidataturaUI
Freelancer -> EditarCandidataturaUI : Mantém/modifica os dados registados
activate EditarCandidataturaUI
EditarCandidataturaUI -> EditarCandidaturaCTRL : updateCandidatura(idCandidatura, valorPretendido, \nnumeroDias, txtApresentacao, txtMotivacao)
activate EditarCandidaturaCTRL
EditarCandidaturaCTRL -> RepositorioCandidatura : updateCandidatura(idCandidatura, valorPretendido, \nnumeroDias, txtApresentacao, txtMotivacao)
activate RepositorioCandidatura
RepositorioCandidatura -> RepositorioCandidatura: update(idCandidatura, valorPretendido, \nnumeroDias, txtApresentacao, txtMotivacao)
RepositorioCandidatura --> EditarCandidaturaCTRL: candidaturaActualizada
deactivate RepositorioCandidatura
EditarCandidaturaCTRL --> EditarCandidataturaUI: candidaturaActualizada
deactivate EditarCandidaturaCTRL
EditarCandidataturaUI --> Freelancer: Candidatura actualizada com sucesso
deactivate EditarCandidataturaUI
end
deactivate Freelancer
@enduml