@startuml
title UC08 - Publicar Tarefa

actor Colaborador
participant ":PublicarTarefaUI" as PublicarTarefaUI
participant ":PublicarTarefaCTRL" as PublicarTarefaCTRL
participant ":Plataforma" as Plataforma
participant "rt:RepositorioTarefa" as RepositorioTarefa
participant "rta:RepositorioAnuncio" as RepositorioAnuncio


activate Colaborador
Colaborador -> PublicarTarefaUI: 1: Inicia o proceso de publicação de tarefa
activate PublicarTarefaUI

PublicarTarefaUI -> PublicarTarefaCTRL: 1.1: lt = listaTarefas()
activate PublicarTarefaCTRL

PublicarTarefaCTRL -> Plataforma: 1.1.1: rt = getRepositorioTarefa()
activate Plataforma
deactivate Plataforma

PublicarTarefaCTRL -> RepositorioTarefa: 1.1.2: lt = listaTarefas()
activate RepositorioTarefa
deactivate PublicarTarefaCTRL
deactivate RepositorioTarefa

PublicarTarefaUI --> Colaborador: 1.2: Mostra a lista de tarefas registadas e solicita a identificação da referência da tarefa a ser publicada
deactivate PublicarTarefaUI

Colaborador -> PublicarTarefaUI: 2: Introduz a referência da tarefa que deseja publicar
activate PublicarTarefaUI

PublicarTarefaUI -> PublicarTarefaCTRL: 2.1: lt = listaTarefas(referencia)
activate PublicarTarefaCTRL

PublicarTarefaCTRL -> RepositorioTarefa : 2.1.1: t = tarefa(referencia)
activate RepositorioTarefa
deactivate RepositorioTarefa
deactivate PublicarTarefaCTRL

PublicarTarefaUI --> Colaborador: 2.2: Mostra a tarefa selecionada e solicita os dados necessários para publicitação desta tarefa
deactivate PublicarTarefaUI

Colaborador -> PublicarTarefaUI: 3: Introduz o período de publicitação, o período de candidaturas e o período de seriação do anúncio da tarefa
activate PublicarTarefaUI

PublicarTarefaUI -> PublicarTarefaCTRL: 3.1: la = novoAnuncio(dtInPub, dtFimPub, dtInCand, dtFimCand, dtInSer, dtFimCand)
activate PublicarTarefaCTRL

PublicarTarefaCTRL -> RepositorioAnuncio : 3.1.1: ra = anuncio(dtInPub, dtFimPub, dtInCand, dtFimCand, dtInSer, dtFimCand)
activate RepositorioAnuncio
deactivate RepositorioAnuncio
deactivate PublicarTarefaCTRL

PublicarTarefaUI --> Colaborador: 3.2: Apresenta os dados e solicita confirmação
deactivate PublicarTarefaUI

Colaborador -> PublicarTarefaUI: 4: Confirma
activate PublicarTarefaUI

PublicarTarefaUI -> PublicarTarefaCTRL: 4.1: registaAnuncio()
activate PublicarTarefaCTRL

PublicarTarefaCTRL -> RepositorioAnuncio : 4.1.1: registaAnuncio(a)
activate RepositorioAnuncio
deactivate PublicarTarefaCTRL

RepositorioAnuncio -> RepositorioAnuncio : 4.1.1.1: valida(a)

RepositorioAnuncio -> RepositorioAnuncio : 4.1.1.2: addAnuncio(a)
deactivate RepositorioAnuncio

PublicarTarefaUI --> Colaborador: 4.2: Informa operação bem sucedida
deactivate PublicarTarefaUI

deactivate Colaborador

@enduml