@startuml
title UC08 - Publicar Tarefa

actor Colaborador
participant ":PublicarTarefaUI" as PublicarTarefaUI
participant ":PublicarTarefaCTRL" as PublicarTarefaCTRL
participant "rt:RepositorioTarefa" as RepositorioTarefa
participant "rta:RepositorioAnuncio" as RepositorioAnuncio
participant "a:Anuncio" as Anuncio

activate Colaborador
Colaborador -> PublicarTarefaUI:  Inicia o proceso de publicação de tarefa
activate PublicarTarefaUI
PublicarTarefaUI -> PublicarTarefaCTRL:  getAllTarefasPorPublicar(nifOrganizacao)
activate PublicarTarefaCTRL
PublicarTarefaCTRL -> RepositorioTarefa: getAllTarefasPorPublicar(nifOrganizacao)
activate RepositorioTarefa
RepositorioTarefa --> PublicarTarefaCTRL: tarefasPorPublicar
deactivate RepositorioTarefa
PublicarTarefaCTRL --> PublicarTarefaUI: tarefasPorPublicar
deactivate PublicarTarefaCTRL
PublicarTarefaUI --> Colaborador: lista de tarefas por publicar
deactivate PublicarTarefaUI


Colaborador -> PublicarTarefaUI: Selecciona a tarefa que pretende publicar
activate PublicarTarefaUI
PublicarTarefaUI -> PublicarTarefaCTRL: findByRefENif(referenciaTarefa, nifOrganizacao)
activate PublicarTarefaCTRL

PublicarTarefaCTRL -> RepositorioTarefa : findByRefENif(referenciaTarefa, nifOrganizacao)
activate RepositorioTarefa
RepositorioTarefa --> PublicarTarefaCTRL: tarefa
deactivate RepositorioTarefa
PublicarTarefaCTRL --> PublicarTarefaUI: tarefa
deactivate PublicarTarefaCTRL

PublicarTarefaUI --> Colaborador: Mostra a tarefa selecionada e \nsolicita os dados necessários \npara publicitação desta tarefa
deactivate PublicarTarefaUI

Colaborador -> PublicarTarefaUI: Introduz o período de publicitação, \no período de candidaturas \ne o período de seriação do anúncio
activate PublicarTarefaUI
PublicarTarefaUI -> PublicarTarefaCTRL: registarAnuncio(dtInPub, dtFimPub, \ndtInCand, dtFimCand, \ndtInSer, dtFimSer, idTipoRegimento)
activate PublicarTarefaCTRL
create Anuncio
PublicarTarefaCTRL -> Anuncio: new Anuncio(dtInPub, dtFimPub, \ndtInCand, dtFimCand, \ndtInSer, dtFimSer, idTipoRegimento)


PublicarTarefaCTRL -> RepositorioAnuncio : save(anuncio)
activate RepositorioAnuncio

RepositorioAnuncio -> RepositorioAnuncio: save(anuncio)
RepositorioAnuncio --> PublicarTarefaCTRL: success
deactivate RepositorioAnuncio
PublicarTarefaCTRL --> PublicarTarefaUI: success
deactivate PublicarTarefaCTRL
PublicarTarefaUI --> Colaborador: Informa operação bem sucedida
deactivate PublicarTarefaUI

deactivate Colaborador

@enduml