@startuml
title UC08 - Publicar Tarefa

'left to right direction

class PublicarTarefaUI{
    --
    -getAllTarefasPorPublicar()
    -findByRefENif(referenciaTarefa, nifOrganizacao)
    -registarAnuncio(dtInPub, dtFimPub, dtInCand, dtFimCand, \ndtInSer, dtFimSer, idTipoRegimento)
    
}

class PublicarTarefaCTRL{
   --
   -getAllTarefasPorPublicar()
   -findByRefENif(referenciaTarefa, nifOrganizacao)
   -new Anuncio((dtInPub, dtFimPub, dtInCand, dtFimCand, \ndtInSer, dtFimSer, idTipoRegimento)
   -save(anunci)
}

class RepositorioAnuncio {
    --
    -save(anuncio)
}

class Anuncio{
    -date dtInicioPublicitacao
    -date dtFimPublicitacao
    -date dtInicioCandidatura
    -date dtFimCandidatura
    -date dtInicioSeriacao
    -date dtFimSeriacao
    -int idTipoRegimento
}

class Tarefa{
    -String referencia
    -String nifOrganizacao
    -String designacao
    -String descInformal
    -String descTecnica
    -int duracaoEst
    -double custoEst 
    -String codigoCategoria
}

class TipoRegimento{
    -int idTipoRegimento
    -String designacao
    -String descricaoRegras
}

class RepositorioAnuncio <<Singleton>>{
    -List<Anuncio> anuncios
    -Anuncio anuncio
    --
}

class RepositorioTarefa <<Singleton>>{
    -List<Tarefa> tarefas
    -Tarefa tarefa
    --
    -allTarefasPorPublicar(nifOrganizacao)
    -tarefa(referencia, nifOrganizacao)    
}

PublicarTarefaUI ..> PublicarTarefaCTRL
PublicarTarefaCTRL ..> RepositorioTarefa
PublicarTarefaCTRL ..> RepositorioAnuncio

RepositorioTarefa "1" --> "1..*" Tarefa: possui >
RepositorioAnuncio "1" --> "1..*"  Anuncio: possui >
Anuncio --> TipoRegimento: exige

@enduml