@startuml
title UC04 - Especificar Competência Técnica

class Plataforma <<Singleton>> {
    -String designacao
}

class EspecificarCompetenciaTecnicaUI{
   getListaAreasAtividade()
   novaCompetenciaTecnica(codCompetencia, descBreve, descDetalhada, codAreaAtividade)
   novoGrau(valor,designacao)
   registaCompetenciaTecnica()
}

class EspecificarCompetenciaTecnicaCTRL{
   getRegistoAreasAtividade()
   getRegistoCompetenciasTecnicas()
   novaCompetenciaTecnica(codCompetencia, descBreve, descDetalhada, at
   registaCompetenciaTecnica(ct)
}

class AreaAtividade{
    String codigo
    String descBreve
    String descDetalhada
}

class CompetenciaTecnica{
    String codigo
    String descBreve
    String descDetalhada
}

class GrauProficiencia{
    Integer valor
    String designacao
}

class RepositorioAreaAtividade <<Singleton>>{
    -List<AreaAtividade>
    -AreaAtividade
    --
    -allAreasAtividade()
    -AreaAtividade(codAreaAtividade)
}

class RepositorioCompetenciaTecnica <<Singleton>>{
    -List<CompetenciaTecnica>
    -CompetenciaTecnica
    --
    -allCompetenciasTecnicas()
    -CompetenciaTecnica(codCompetencia)
}

EspecificarCompetenciaTecnicaUI ..> EspecificarCompetenciaTecnicaCTRL

EspecificarCompetenciaTecnicaCTRL ..> Plataforma

EspecificarCompetenciaTecnicaCTRL ..> RepositorioAreaAtividade

EspecificarCompetenciaTecnicaCTRL ..> RepositorioCompetenciaTecnica

RepositorioAreaAtividade "1" --> "1..*" AreaAtividade

RepositorioCompetenciaTecnica "1" --> "1..*" CompetenciaTecnica

CompetenciaTecnica --> GrauProficiencia

@enduml