@startuml

title UC10 - Seriação (Não Automática) de Candidaturas

actor "Colaborador da Organização" as Colaborador
actor ":Sistema" as Sistema
activate "Colaborador da Organização"

Colaborador -> Sistema : 1 inicia o processo não automático de seriação dos candidatos à realização de um anúncio
activate Sistema

Sistema --> Colaborador: 2 mostra os anúncios publicados pelo colaborador em fase de seriação não automática, e que ainda não foram seriados, e pede-lhe para escolher um
deactivate Sistema

Colaborador -> Sistema: 3 seleciona um anúncio
activate Sistema

Sistema --> Colaborador: 4 mostra as candidaturas existentes e solicita a sua classificação
deactivate Sistema

loop 

Colaborador -> Sistema: 5 classifica a candidatura
activate Sistema

end

Sistema --> Colaborador: 6 mostra os colaboradores da organização e pede para selecionar outros participantes
deactivate Sistema

loop

Colaborador -> Sistema: 7 seleciona outros colaboradores participantes
activate Sistema

end

Sistema --> Colaborador: 8 apresenta os dados e solicita confirmação
deactivate Sistema

Colaborador -> Sistema: 9 confirma
activate Sistema

Sistema --> Colaborador: 10 informa o sucesso da operação
deactivate Sistema

deactivate Colaborador

@enduml