@startuml

title UC5 - Especificar colaborador da Organização

Actor "Gestor da Organização"
activate "Gestor da Organização"
"Gestor da Organização" -> Sistema: 1 Inicia a especificação de um colaborador da sua Organização
activate Sistema
Sistema --> "Gestor da Organização": 2 Solicita os dados (nome, função, contacto telefónico, endereço de email)
deactivate Sistema
"Gestor da Organização" -> Sistema: 3 Introduz os dados solicitados
activate Sistema
Sistema --> "Gestor da Organização": 4 Apresenta os dados e solicita confirmação
deactivate Sistema
"Gestor da Organização" -> Sistema: 5 confirma os dados
activate Sistema
Sistema --> "Gestor da Organização": 6 Informa do sucesso da operação
deactivate Sistema
deactivate "Gestor da Organização"
@enduml
