@startuml

title UC01 - Registar Organização - Diagrama de Sequência de Sistema

actor "Utilizador Não Registado" as UtilizadorNaoRegistado
activate UtilizadorNaoRegistado

skinparam sequenceMessageAlign left
UtilizadorNaoRegistado -> Sistema: 1. Registar Organização
Sistema --> UtilizadorNaoRegistado: 2. Solicita dados da organização (nome, NIF, endereço, telefone, website, email) e sobre o gestor (nome, funçao, telefone, email)

UtilizadorNaoRegistado -> Sistema: 3. Introduz os dados solicitados
UtilizadorNaoRegistado <-- Sistema: 4. Operação bem sucedida

@enduml