@startuml

title UC01 - Registar Organização - Diagrama de Sequência

actor "Utilizador Não Registado" as UtilizadorNaoRegistado
participant ":RegistarOrganizacaoUI" as RegistarOrganizacaoUI
participant ":RegistarOrganizacaoController" as RegistarOrganizaoController
participant "ro:RepositorioOrganizacao" as RepositorioOrganizacao
participant "colab:Colaborador" as Colaborador
participant "org:Organizacao" as Organizacao
participant "end:EnderecoPostal" as EnderecoPostal

UtilizadorNaoRegistado -> RegistarOrganizacaoUI: 1 Introduz os dados solicitados
activate RegistarOrganizacaoUI
RegistarOrganizacaoUI ->  RegistarOrganizaoController: 2 registarOrganizacao(nif, nome, website, \ntelefoneOrg, emailOrg, \nendArruamento, endPorta, endLocalidade, endCodPostal, \nnomeGestor, telefoneGestor, funcaoGestor)
activate RegistarOrganizaoController
RegistarOrganizaoController -> RepositorioOrganizacao: 3 org = save(registarOrganizacao(nif, nome, website, \ntelefoneOrg, emailOrg, \nendArruamento, endPorta, endLocalidade, endCodPostal, \nnomeGestor, telefoneGestor, funcaoGestor)
activate RepositorioOrganizacao
RepositorioOrganizacao -> EnderecoPostal: 4 create(endLocal, endCodPostal, endLocalidade)
activate EnderecoPostal
EnderecoPostal --> RepositorioOrganizacao: 5 end
deactivate EnderecoPostal
RepositorioOrganizacao -> Colaborador: 6 createUtilizador(nomeG, tlfG, emailG, password)
ref over Plataforma, Organizacao : UC1_SD_RegistarGestorComoUtilizador
activate Colaborador
RepositorioOrganizacao -> Colaborador: 7 createGestor(nomeG, função, tlfG, emailG)
Colaborador --> RepositorioOrganizacao: colaboradorComoGestor
deactivate Colaborador
RepositorioOrganizacao --> Organizacao : 8 create(nome, NIF, end, tlf, site, email, colab)
activate Organizacao
Organizacao --> RepositorioOrganizacao: 9 org
deactivate Organizacao
RepositorioOrganizacao --> RegistarOrganizaoController: 10 org
deactivate RepositorioOrganizacao
RegistarOrganizaoController --> RegistarOrganizacaoUI: 11 org
RegistarOrganizacaoUI --> Colaborador: 12 Registo bem sucedido



@enduml