@startuml

title UC10-B - Seriar Candidaturas de Anúncio (automaticamente)

participant Colaborador
participant SeriarCandidaturasUI
participant SeriarCandidaturasCtrl
participant RepositorioAnuncio
participant RepositorioCandidatura
participant RepositorioClassificacao
participant RepositorioSeriacao


activate Colaborador
Colaborador -> SeriarCandidaturasUI: Consulta anúncios em periodo \nde seriação
activate SeriarCandidaturasUI
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: listaAnunciosASeriar\n(emailColaborador, nifOrganizacao)
activate SeriarCandidaturasCtrl
SeriarCandidaturasCtrl -> RepositorioAnuncio: listaAnunciosASeriar\n(emailColaborador, nifOrganizacao)
activate RepositorioAnuncio

alt (Não existem anúncios a seriar)
RepositorioAnuncio --> SeriarCandidaturasCtrl: listaAnunciosASeriar\n(emailColaborador, \nnifOrganizacao) = null
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: listaAnunciosASeriar\n(emailColaborador, \nnifOrganizacao) = null
SeriarCandidaturasUI --> Colaborador: Não existem anúncios \ndisponiveis

else Existem anúncios a seriar 
RepositorioAnuncio --> SeriarCandidaturasCtrl: listaAnunciosASeriar\n(emailColaborador, \nnifOrganizacao) 
deactivate RepositorioAnuncio
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: listaAnunciosASeriar\n(emailColaborador, \nnifOrganizacao)
deactivate SeriarCandidaturasCtrl
SeriarCandidaturasUI --> Colaborador: Mostra a lista das referências \nde Tarefa dos Anúncios a \nseriar 
deactivate SeriarCandidaturasUI


Colaborador -> SeriarCandidaturasUI: Seleciona um anúncio de \nregimento Automático a seriar 
activate SeriarCandidaturasUI
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: getAllByIdAnuncio(idAnuncio)
activate SeriarCandidaturasCtrl
SeriarCandidaturasCtrl -> RepositorioCandidatura: getAllByIdAnuncio(idAnuncio)
activate RepositorioCandidatura

alt  Não existem candidaturas ao anúncio selecionado
RepositorioCandidatura --> SeriarCandidaturasCtrl: candidaturas(idAnuncio) = null
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: candidaturas(idAnuncio) = null
SeriarCandidaturasUI --> Colaborador: Não existem candidaturas disponíveis

else Existem candidaturas ao anúncio selecionado
RepositorioCandidatura --> SeriarCandidaturasCtrl: candidaturas(idAnuncio)
deactivate RepositorioCandidatura
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: candidaturas(idAnuncio)
deactivate SeriarCandidaturasCtrl
SeriarCandidaturasUI --> Colaborador: Mostra a lista de candidaturas \nao anúncio e solicita \ninformar se deseja prosseguir \nna classificação automática \ndas candidaturas
deactivate SeriarCandidaturasUI

Colaborador -> SeriarCandidaturasUI: O colaborador confirmar o \nprosseguimento da operação
activate SeriarCandidaturasUI
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: ordenarByValor(candidaturas)
activate SeriarCandidaturasCtrl
SeriarCandidaturasCtrl -> RepositorioCandidatura: ordenarByValor(candidaturas)
activate RepositorioCandidatura
RepositorioCandidatura --> SeriarCandidaturasCtrl: candidaturasOrdenadas(candidaturas)
deactivate RepositorioCandidatura
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: saveSeriacao(idAnuncio)
SeriarCandidaturasCtrl -> RepositorioSeriacao : saveSeriacao(idAnuncio)
activate RepositorioSeriacao
RepositorioSeriacao -> RepositorioSeriacao: save(idAnuncio)
RepositorioSeriacao --> SeriarCandidaturasCtrl: Seriação criada com sucesso
deactivate RepositorioSeriacao
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: Seriação criada com sucesso
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: getIdSeriacao(idAnuncio)
SeriarCandidaturasCtrl -> RepositorioSeriacao: getIdSeriacao(idAnuncio)
activate RepositorioSeriacao
RepositorioSeriacao -> RepositorioSeriacao: getProcessoSeriacaoByAnuncio(idAnuncio).getIdSeriacao()
RepositorioSeriacao --> SeriarCandidaturasCtrl: idSeriacao
deactivate RepositorioSeriacao
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: idSeriacao
SeriarCandidaturasUI -> SeriarCandidaturasCtrl: saveClassificacaoAutomatica\n(candidaturasOrdenadas, idSeriacao)
SeriarCandidaturasCtrl -> RepositorioClassificacao: saveClassificacaoAutomatica\n(candidaturasOrdenadas, idSeriacao)
activate RepositorioClassificacao
loop
RepositorioClassificacao -> RepositorioClassificacao: (posicao, idSeriacao, idCandidatura)
end loop
RepositorioClassificacao --> SeriarCandidaturasCtrl: Classificação salva com sucesso
deactivate RepositorioClassificacao
SeriarCandidaturasCtrl --> SeriarCandidaturasUI: Classificação salva com sucesso
deactivate SeriarCandidaturasCtrl
SeriarCandidaturasUI --> Colaborador: Mostra a lista seriada \nde candidaturas \ne informa o sucesso no \nprocesso de seriação
deactivate SeriarCandidaturasUI
end alt 
end alt
deactivate Colaborador
@enduml