@startuml
title UC03 - Definir Categoria de Tarefa

class Plataforma <<Singleton>> {
    -String designacao
}

class DefinirCategoriaTarefaUI{
   getListaAreasAtividade()
   novaAreaAtividade(descricao, codAreaAtividade)
   getGrausProficiencia(codCompetencia)
   setProficienciaObrigatoriedade(codGrau, obrigatoria)
   registaCategoria()
}

class DefinirCategoriaTarefaCTRL{
   getRegistoCategorias()
   novaCategoria(descricao, at)
   getGrausProficiencia(ct)
   getGrauProficiencia(codGrau)
   novaCaracterizacao(ct, gp, obrigatoria)
   registaCategoria(c)
}

class AreaAtividade{
    String codigo
    String descBreve
    String descDetalhada
}

class CompetenciaTecnica{
    String codigo
    String descBreve
    String descDetalhada
}

class Categoria{
    String id 
    String descricao
}

class GrauProficiencia{
    Integer valor
    String designacao
}

class CaracterCT{
    Boolean obrigatoria
}

class CaracterizacaoCT{
    
}

class RepositorioAreaAtividade <<Singleton>>{
    -List<AreaAtividade>
    -AreaAtividade
    --
    -allAreasAtividade()
    -AreaAtividade(codAreaAtividade)
}

class RepositorioCompetenciaTecnica <<Singleton>>{
    -List<CompetenciaTecnica>
    -CompetenciaTecnica
    --
    -allCompetenciasTecnicas()
    -CompetenciaTecnica(codCompetencia)
}

class RepositorioCategoria <<Singleton>>{
    -List<Categoria>
    -Categoria
    --
    -allCategorias()
    -Categoria(codCat)
}



DefinirCategoriaTarefaUI ..> DefinirCategoriaTarefaCTRL

DefinirCategoriaTarefaCTRL ..> Plataforma

DefinirCategoriaTarefaCTRL ..> RepositorioAreaAtividade

DefinirCategoriaTarefaCTRL ..> RepositorioCategoria

DefinirCategoriaTarefaCTRL ..> RepositorioCompetenciaTecnica

RepositorioAreaAtividade "1" --> "1..*" AreaAtividade: possui >

RepositorioCategoria "1" --> "1..*"  Categoria: possui >

RepositorioCompetenciaTecnica "1" --> "1..*" CompetenciaTecnica: possui >

@enduml