@startuml

actor "Gestor da Organização" as GestorOrganizacao
participant ":EspecificarColaboradorUI" as EspecificarColaboradorUI
participant ":EspecificarColaboradorCTRL" as EspecificarColaboradorCTRL
participant "gu:GestãoUtilizadoresCTRL" as GestaoUtilizadoresCTRL
participant "ro:RepositorioOrganizacao" as RepositorioOrganizacao
participant "rc:RepositorioColaborador" as RepositorioColaborador
participant "c:Colaborador" as Colaborador
participant "u:Utilizador" as Utilizador
participant "agp:getAlgoritmoGeradorPasswords" as AlgoritmoGeradorPasswords

activate GestorOrganizacao
GestorOrganizacao -> EspecificarColaboradorUI: Inicia a especificação de um colaborador da Organização
activate EspecificarColaboradorUI
EspecificarColaboradorUI --> GestorOrganizacao: Solicita os dados
deactivate EspecificarColaboradorUI
GestorOrganizacao -> EspecificarColaboradorUI: Introduz os dados
activate EspecificarColaboradorUI
EspecificarColaboradorUI -> EspecificarColaboradorCTRL: novoColaborador(nome, funcao, telefone, email)
activate EspecificarColaboradorCTRL

EspecificarColaboradorCTRL -> GestaoUtilizadoresCTRL: getSessaoActual()
activate GestaoUtilizadoresCTRL
GestaoUtilizadoresCTRL --> EspecificarColaboradorCTRL: sessaoActual
EspecificarColaboradorCTRL -> GestaoUtilizadoresCTRL: getEmail() 
GestaoUtilizadoresCTRL --> EspecificarColaboradorCTRL: emailGestor()
deactivate GestaoUtilizadoresCTRL

EspecificarColaboradorCTRL -> RepositorioOrganizacao: findNifByEmail(emailGestor)
activate RepositorioOrganizacao
RepositorioOrganizacao --> EspecificarColaboradorCTRL: nifOrganizacao
deactivate RepositorioOrganizacao
EspecificarColaboradorCTRL -> AlgoritmoGeradorPasswords: geraPassword()
activate AlgoritmoGeradorPasswords
AlgoritmoGeradorPasswords --> EspecificarColaboradorCTRL: password
deactivate AlgoritmoGeradorPasswords
create Utilizador
EspecificarColaboradorCTRL -> Utilizador: new Utilizador(nome, email, password, rolename)
EspecificarColaboradorCTRL -> GestaoUtilizadoresCTRL: registerUserWithRoles(nome, email, password, rolename)
activate GestaoUtilizadoresCTRL
GestaoUtilizadoresCTRL --> EspecificarColaboradorCTRL: utilizador
deactivate GestaoUtilizadoresCTRL
create Colaborador
EspecificarColaboradorCTRL -> Colaborador: new Colaborador(nome, email, password, funcao, telefone, nifOrganizacao)
EspecificarColaboradorCTRL -> RepositorioColaborador: save(nome, email, password, funcao, telefone, nifOrganizacao)
activate RepositorioColaborador
RepositorioColaborador --> EspecificarColaboradorCTRL: colaborador
deactivate RepositorioColaborador

EspecificarColaboradorCTRL --> EspecificarColaboradorUI: colaborador, password
deactivate EspecificarColaboradorCTRL
EspecificarColaboradorUI --> GestorOrganizacao: passwordColaborador, colaborador registado com sucesso




@enduml