@startuml

title UC5 - Especificar colaborador da Organização

Actor "Gestor de Organização" as GestorOrganizacao


activate GestorOrganizacao
GestorOrganizacao -> Sistema: 1 Inicia a especificação de um colaborador da sua Organização
activate Sistema
Sistema --> GestorOrganizacao: 2 Solicita os dados (nome, função, contacto telefónico, endereço de email)
deactivate Sistema
GestorOrganizacao -> Sistema: 3 Introduz os dados solicitados
activate Sistema
Sistema --> GestorOrganizacao: 4 Apresenta os dados e solicita confirmação
deactivate Sistema
GestorOrganizacao -> Sistema: 5 confirma os dados
activate Sistema
Sistema --> GestorOrganizacao: 6 Informa do sucesso da operação
deactivate Sistema
deactivate GestorOrganizacao
@enduml
