@startuml

left to right direction
title Modelo Relacional

hide circle
'skinparam linetype ortho

entity "Plataforma" {
    designacao: text
}

entity "Organizacao" {
    nif: text {PK}     
    --
    nome: text {NN}
    website: text
    telefone: text {NN}
    email: text {NN}
}

entity "Colaborador" {
    funcao: text
    telefone: text
    gestor:boolean {NN}
    nifOrganizacao: text {FK}
}

entity "Utilizador" {
    email: text {PK}
    --
    nome: text {NN}
    password: text {NN}
}

entity "Administrativo" {
}

entity "Categoria" {
    idCategoria: text {PK}
    --
    descricao: text
}

entity "CompetenciaTecnica" {
    codigoCompTecnica: text {PK}
    --
    descBreve: text
    descDetalhada: text
}

entity "CategoriaCompTecnica" {
    codigoCompTecnica: text {PK, FK}
    idCategoria: text {PK, FK}
}

entity "AreaActividade" {
    codigoAreaActividade: text {PK}
    --
    descBreve: text
    descDetalhada: text
}

entity "GrauProficiencia" {
    idGrauProficiencia: text {PK}
    --
    valor: integer 
    designacao: text 
    codigoCompTecnica: text {FK}
}

entity "Freelancer" {
    nif: text {PK}
    --
    telefone: text
}

entity "CandidatoFreelancer" {
    nif: text {PK}
    --
    nome: text
    email: text
    telefone: text
    enderecoPostal {FK}
}

entity "EnderecoPostal" {
    arruamento: text {PK}
    numeroPorta: text {PK}
    localidade: text {PK}
    codigoPostal: text {PK}
}

entity "Tarefa" {
    referencia: text {PK}
    --
    designacao: text
    descInformal: text
    descTecnica: text
    duracaoEstimada: integer
    custoEstimado: number
}

entity "Anuncio" {
    idAnuncio {PK}
    --
    dataInicioPublicacao: date
    dataFimPublicacao: date
    dataInicioCandidatura: date
    dataFimCandidatura: date
    dataInicioSeriacao
    dataFimSeriacao
}

entity "ProcessoSeriacao" {
    idProcessoSeriacao: text {PK}
    --
    dataRealizacao: date
    idTipoRegimento: text {FK}
}

entity "TipoRegimento" {
    idTipoRegimento: text {PK}
    --
    designacao: text
    descricaoRegras: text
}

entity "Classificacao" {
    idClassificacao: integer {PK}
    --
    lugar: integer
    idProcessoSeriacao: text {FK}
}

entity "Candidatura" {
    idCandidatura: text {PK}
    --
    dataFimCandidatura: date
    valorPretendido: number
    numeroDias: integer
    txtApresentacao: text
    txtMotivacao: text
    idAnuncio: text {FK}
    idProcessoSeriacao: text {FK}
}

entity "HabilitacaoAcademica" {
    idHabilitacaoAcademica {PK}
    --
    grau: text 
    designacaoCurso: text 
    nomeInstituicao: text 
    mediaCurso: number
}

entity "ReconhecimentoCT" {
    idReconhecimntoCT: text {PK}
    --
    dataReconhecimento: date
    codigoCompTecnica: text {FK}
}

entity "FreelancerHabAcademica" {
    emailFreelancer: text {PK, FK}
    idHabilitacaoAcademica: text {PK, FK}
}

entity "FreelancerReconhecimentoCT" {
    emailFreelancer: text {PK, FK}
    idReconhecimntoCT: text {PK, FK}

}
entity "CaracterCT" {
    obrigatoria: boolean
}

Plataforma ||--|{ Organizacao
Plataforma ||--|{ Administrativo
AreaActividade ||--|{ Categoria
Plataforma ||--|{ CompetenciaTecnica
Plataforma ||--|{ AreaActividade
Plataforma ||--|{ Freelancer
Freelancer --|> Utilizador
Administrativo --|> Utilizador
AreaActividade ||--|{ CompetenciaTecnica
CompetenciaTecnica ||--|{ GrauProficiencia
Organizacao ||--|{ Tarefa
Categoria ||--|{ Tarefa
Tarefa ||--o| Anuncio
Organizacao ||--|{ Colaborador
Colaborador --|> Utilizador
CandidatoFreelancer ||--o| Freelancer
Anuncio ||--|{ Candidatura
Freelancer||--|{ Candidatura
Organizacao ||--|| EnderecoPostal
Freelancer ||--|| EnderecoPostal
Candidatura ||--|| ProcessoSeriacao
ProcessoSeriacao ||--|| TipoRegimento
ProcessoSeriacao ||--|{ Classificacao
Freelancer ||--|{ FreelancerHabAcademica
HabilitacaoAcademica ||--|{ FreelancerHabAcademica
Freelancer ||-|{ FreelancerReconhecimentoCT
ReconhecimentoCT ||--|{ FreelancerReconhecimentoCT
Reconhecimento }|--|| CompetenciaTecnica
CaracterCT ||--|{ CompetenciaTecnica









@enduml