@startuml

title UC05 - Especificar Colaborador

left to right direction

class Plataforma <<Singleton>> {
    -String designacao
    --
    getRepositorioOrganizacao()
}

class EspecificarColaboradorUI{
    --
    -novoColaborador(nome, funcao, telefone, email)
    -registaColaborador()

}

class EspecificarColaboradorCTRL{
    --
    novoColaborador(nome, funcao, telefone, email)
    validaColaborador(c)
    registaColaborador(c)
    registaUtilizadorComPapel(nome, email, password, "colaborador")
}

class Organizacao {
    -String nome
    -String NIF
    -String website
    -String telefone
    -Email email
}

class Colaborador {
    -String funcao
    -String telefone
    -Organizacao organizacao
}

class Utilizador {
    -String nome
    -Email email
    -Password password
}

class GestaoUtilizadoresFacade{
    getGestaoUtilizadoresFacade()
}

class SessaoAtual{
    --
    getSessaoAtual()
}

class SessaoUtilizador{
    --
    getEmailUtilizador()
}

class RepositorioOrganizacao{
    --
    organizacaoByEmailUtilizador(email)
}

interface AlgoritmoGeradorPasswords{
    getAlgoritmoGeradorPasswords()
}

class Password{
    String password
    --
    getPassword()
}

class UtilizadorComPapel{
}


class Email {
    -String email
    --
    getEmailUtilizador()
}

EspecificarColaboradorUI ..> EspecificarColaboradorCTRL
EspecificarColaboradorCTRL ..> Plataforma
EspecificarColaboradorCTRL ..> GestaoUtilizadoresFacade
EspecificarColaboradorCTRL ..> SessaoUtilizador
Organizacao -- Colaborador: possui >
Colaborador --|> UtilizadorComPapel
UtilizadorComPapel --|> Utilizador
Email -- Utilizador: < possui
Password -- Utilizador: < possui
Email -- Organizacao: < possui
Organizacao -- RepositorioOrganizacao
Colaborador -- SessaoAtual: tem >
EspecificarColaboradorCTRL ..> UtilizadorComPapel
EspecificarColaboradorCTRL ..> AlgoritmoGeradorPasswords
Plataforma ..> RepositorioOrganizacao


@enduml